### ISSUE TITLE
FileSystemException,Show Blank Screen on mac m1 after issuing flutter run -d macos

### ISSUE THREAD

**Issue by goldcoders** [leoafarias/sidekick#106]
OS: macOS 11.4 20F71 arm64
Flutter version 2.2.2

<img width="813" alt="Screen Shot 2021-07-04 at 7 36 46 AM" src="https://user-images.githubusercontent.com/55337687/124369091-9fdbf980-dc9a-11eb-97e6-8da33f29c7d5.png">

```
2021-07-04 07:31:04.445 Sidekick[38573:441063] NSWindow warning: adding an unknown subview: <NSVisualEffectView: 0x7fd5b176d310>. Break on NSLog to debug.
2021-07-04 07:31:04.469 Sidekick[38573:441063] Call stack:
(
	0   AppKit                              0x00007fff22b89d55 -[NSThemeFrame addSubview:] + 112
	1   AppKit                              0x00007fff22bcdf6c -[NSView replaceSubview:with:] + 154
	2   Sidekick                            0x0000000104f56d27 $s8Sidekick17MainFlutterWindowC12awakeFromNibyyF + 1623
	3   Sidekick                            0x0000000104f5706b $s8Sidekick17MainFlutterWindowC12awakeFromNibyyFTo + 43
	4   CoreFoundation                      0x00007fff2042c25c -[NSSet makeObjectsPerformSelector:] + 215
	5   AppKit                              0x00007fff22b3f086 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1368
	6   AppKit                              0x00007fff22b33778 loadNib + 392
	7   AppKit                              0x00007fff22b32d84 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 693
	8   AppKit                              0x00007fff22b329da -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	9   AppKit                              0x00007fff22b327b8 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 394
	10  AppKit                              0x00007fff22b25382 NSApplicationMain + 566
	11  Sidekick                            0x0000000104f57e9d main + 13
	12  libdyld.dylib                       0x00007fff20359f5d start + 1
	13  ???                                 0x0000000000000001 0x0 + 1
)
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Cannot copy file to '/Users/uriah/Library/Application Support/app.fvm.sidekick/settings_box.lock', path = '/Users/uriah/Documents/settings_box.lock' (OS Error: Interrupted system call, errno = 4)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      checkMigration (package:sidekick/src/modules/common/utils/migrateFiles.dart:28:12)
<asynchronous suspension>
#3      main (package:sidekick/main.dart:31:3)
<asynchronous suspension>
```

**Comment by aguilaair** [comment]
Hey! Seems that there was an issue migrating the settings to the new location. Let me investigate this
