### ISSUE TITLE
Can only check flutter settings with a global version configured.

### ISSUE THREAD

**Issue by SirusCodes** [leoafarias/sidekick#56]
I got this error while build it on Windows 10

```console
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Exception: Can only check flutter settings with a global version configured
#0      FlutterConfigService._runCmd (package:sidekick/services/flutter_config_service.dart:17:7)
<asynchronous suspension>
#1      FlutterConfigService.getFlutterConfig (package:sidekick/services/flutter_config_service.dart:58:20)
<asynchronous suspension>
#2      SettingsProvider._loadState (package:sidekick/providers/settings.provider.dart:100:29)
<asynchronous suspension>

Activating Dart DevTools...                                        15.2s
Syncing files to device Windows...                                 317ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:51377/H8sRE4BdDvg=/

Flutter DevTools, a Flutter debugger and profiler, on Windows is available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A51377%2FH8sRE4BdDvg%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'fvm' was called on null.
Receiver: null
Tried calling: fvm
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SettingsProvider._checkFvmSettingsChanges (package:sidekick/providers/settings.provider.dart:85:43)
#2      SettingsProvider.save (package:sidekick/providers/settings.provider.dart:120:13)
#3      SettingsScreen.build.handleSave (package:sidekick/screens/settings_screen.dart:58:24)
#4      SettingsScreen.build.handleSave (package:sidekick/screens/settings_screen.dart:56:28)
#5      SettingsSectionGeneral.build.<anonymous closure> (package:sidekick/screens/settings_scenes/settings_section_general.dart:98:23)
#6      SettingsSectionGeneral.build.<anonymous closure> (package:sidekick/screens/settings_scenes/settings_section_general.dart:96:26)
#7      _DropdownButtonState._handleTap.<anonymous closure> (package:flutter/src/material/dropdown.dart:1255:26)
#8      _rootRunUnary (dart:async/zone.dart:1362:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:539:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#15     _rootRun (dart:async/zone.dart:1354:13)
#16     _CustomZone.run (dart:async/zone.dart:1258:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

I guess it is not able to find the path to fvm.

**Comment by leoafarias** [comment]
Creating a better UI to show, however, I have still have to see what is the best way to work around this.

**Comment by SirusCodes** [comment]
I couldn't understand how to fix it🤔
Do I need to set global Flutter version in fvm?

**Comment by leoafarias** [comment]
yes you have to configured a global version, I will create better docs, but on the Installed versions click on the menu on the right side of the version and select "Set as Global"

**Comment by leoafarias** [comment]
@SirusCodes I will go ahead and close this since the updated notification and UI were in latest version
